# PRACTICAL QUESTION FOUR

In [ ]:
# Construct a matrix below;as a numpy array
[{1 ,0.2 ,0.5},{0.2,1,0.8},{0.5,0.8,1}]

#compute an inversion of the matrix (Transpose)
#Compute the (determinant)of the matrix if possible
# Decompose the matrix
#Transform the matrix

In [1]:
import numpy as np

In [3]:
#Constructing the martix as a numpy array
matrix=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [6]:
#Compute an inversion of the matrix(Transpose)
inverse=np.linalg.inv(matrix)
print("Inverse of the matrix:")
print(inverse)

Inverse of the matrix:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [7]:
#Compute the (determinant)of the matrix if possible
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:")
print(determinant)

Determinant of the matrix:
0.2299999999999999


In [8]:
#Decompose the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues of the matrix:")
print(eigenvalues)

print("Eigenvectors of the matrix:")
print(eigenvectors)


Eigenvalues of the matrix:
[2.04100779 0.82188052 0.13711169]
Eigenvectors of the matrix:
[[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


In [9]:
# Transform the matrix
transformed_matrix = np.dot(matrix, matrix)
print("Transformed matrix:")
print(transformed_matrix)

Transformed matrix:
[[1.29 0.8  1.16]
 [0.8  1.68 1.7 ]
 [1.16 1.7  1.89]]


# QUESTION FIVE

In [ ]:
# Write a python program to solve three linear equations using matrices .You can use the numpy library for matrix operations

In [57]:
import numpy as np

In [58]:
# Define the coefficients matrix A
A = np.array([[1, 2, -5],
              [7, -9, 3],
              [4, 5, -2]])
print(A)


[[ 1  2 -5]
 [ 7 -9  3]
 [ 4  5 -2]]


In [59]:
# Define the constant terms vector B
B=np.array([4,2,-1])
print(B)

[ 4  2 -1]


In [63]:
#Solve the linear equations Ax=B
x=np.linalg.solve(A,B)
print("The solution is:", x)

The solution is: [-0.03       -0.59333333 -1.04333333]
